--
-- PostgreSQL database dump
--

\restrict HOe1AsBcUHntUtjqfPmDJvhHMUwtlE3EhHnnojtqh5exmZO6g9AituaIL7PqCBg

-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auditoria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auditoria (
    id bigint NOT NULL,
    accion character varying(255),
    entidad character varying(255),
    fecha timestamp(6) without time zone,
    registro_id bigint,
    usuario character varying(255)
);


--
-- Name: auditoria_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auditoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auditoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: configuracion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.configuracion (
    id bigint NOT NULL,
    anio_activo integer,
    cif character varying(255),
    direccion character varying(255),
    email character varying(255),
    iban character varying(255),
    importe_cuota_costalero numeric(38,2),
    importe_cuota_hermano numeric(38,2),
    nombre_hermandad character varying(255),
    telefono character varying(255)
);


--
-- Name: configuracion_cuadrillas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.configuracion_cuadrillas (
    id bigint NOT NULL,
    columnas integer NOT NULL,
    filas integer NOT NULL,
    nombre character varying(120) NOT NULL
);


--
-- Name: configuracion_cuadrillas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.configuracion_cuadrillas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.configuracion_cuadrillas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cuotas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cuotas (
    id bigint NOT NULL,
    anio integer,
    estado character varying(255),
    fecha_pago date,
    importe numeric(38,2),
    observaciones character varying(255),
    tipo character varying(255) NOT NULL,
    socio_id bigint,
    CONSTRAINT cuotas_estado_check CHECK (((estado)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'PAGADA'::character varying, 'ANULADA'::character varying])::text[]))),
    CONSTRAINT cuotas_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['HERMANO'::character varying, 'COSTALERO'::character varying])::text[])))
);


--
-- Name: cuotas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cuotas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuotas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventario (
    id bigint NOT NULL,
    activo boolean NOT NULL,
    categoria character varying(255) NOT NULL,
    codigo character varying(255) NOT NULL,
    descripcion character varying(2000),
    estado character varying(255) NOT NULL,
    fecha_adquisicion date,
    imagen_url character varying(255),
    nombre character varying(255) NOT NULL,
    observaciones character varying(2000),
    ubicacion character varying(255) NOT NULL,
    valor_adquisicion numeric(12,2),
    CONSTRAINT inventario_estado_check CHECK (((estado)::text = ANY ((ARRAY['BUENO'::character varying, 'REGULAR'::character varying, 'DETERIORADO'::character varying, 'RESTAURACION'::character varying, 'EXTRAVIADO'::character varying])::text[])))
);


--
-- Name: inventario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: revisiones_inventario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.revisiones_inventario (
    id bigint NOT NULL,
    estado character varying(255) NOT NULL,
    fecha timestamp(6) without time zone NOT NULL,
    observaciones character varying(2000),
    titulo character varying(255) NOT NULL,
    usuario character varying(255) NOT NULL,
    CONSTRAINT revisiones_inventario_estado_check CHECK (((estado)::text = ANY ((ARRAY['ABIERTA'::character varying, 'CERRADA'::character varying])::text[])))
);


--
-- Name: revisiones_inventario_detalle; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.revisiones_inventario_detalle (
    id bigint NOT NULL,
    estado_observado character varying(255),
    fecha_verificacion timestamp(6) without time zone,
    incidencia character varying(2000),
    ubicacion_observada character varying(255),
    verificado boolean NOT NULL,
    elemento_id bigint NOT NULL,
    revision_id bigint NOT NULL,
    CONSTRAINT revisiones_inventario_detalle_estado_observado_check CHECK (((estado_observado)::text = ANY ((ARRAY['BUENO'::character varying, 'REGULAR'::character varying, 'DETERIORADO'::character varying, 'RESTAURACION'::character varying, 'EXTRAVIADO'::character varying])::text[])))
);


--
-- Name: revisiones_inventario_detalle_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.revisiones_inventario_detalle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.revisiones_inventario_detalle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: revisiones_inventario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.revisiones_inventario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.revisiones_inventario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: socios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.socios (
    id bigint NOT NULL,
    apellidos character varying(255) NOT NULL,
    cuadrilla character varying(120),
    direccion character varying(255),
    dni character varying(9) NOT NULL,
    email character varying(255),
    estado character varying(255),
    fecha_alta date,
    fecha_creacion timestamp(6) without time zone,
    fecha_modificacion timestamp(6) without time zone,
    fecha_nacimiento date,
    forma_pago character varying(255),
    iban character varying(34),
    nombre character varying(255) NOT NULL,
    numero_socio integer,
    posicion_cuadrilla integer,
    telefono character varying(255),
    tipo character varying(255) NOT NULL,
    titular_cuenta character varying(255),
    CONSTRAINT socios_estado_check CHECK (((estado)::text = ANY ((ARRAY['ACTIVO'::character varying, 'BAJA'::character varying, 'FALLECIDO'::character varying, 'SUSPENDIDO'::character varying])::text[]))),
    CONSTRAINT socios_forma_pago_check CHECK (((forma_pago)::text = ANY ((ARRAY['EFECTIVO'::character varying, 'TRANSFERENCIA'::character varying, 'DOMICILIACION'::character varying])::text[]))),
    CONSTRAINT socios_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['HERMANO'::character varying, 'COSTALERO'::character varying])::text[])))
);


--
-- Name: socios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.socios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    activo boolean,
    password character varying(255),
    rol character varying(255),
    username character varying(255),
    CONSTRAINT usuarios_rol_check CHECK (((rol)::text = ANY ((ARRAY['ADMIN'::character varying, 'TESORERO'::character varying, 'SECRETARIO'::character varying, 'CONSULTA'::character varying])::text[])))
);


--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auditoria auditoria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auditoria
    ADD CONSTRAINT auditoria_pkey PRIMARY KEY (id);


--
-- Name: configuracion_cuadrillas configuracion_cuadrillas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.configuracion_cuadrillas
    ADD CONSTRAINT configuracion_cuadrillas_pkey PRIMARY KEY (id);


--
-- Name: configuracion configuracion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.configuracion
    ADD CONSTRAINT configuracion_pkey PRIMARY KEY (id);


--
-- Name: cuotas cuotas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cuotas
    ADD CONSTRAINT cuotas_pkey PRIMARY KEY (id);


--
-- Name: inventario inventario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario
    ADD CONSTRAINT inventario_pkey PRIMARY KEY (id);


--
-- Name: revisiones_inventario_detalle revisiones_inventario_detalle_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.revisiones_inventario_detalle
    ADD CONSTRAINT revisiones_inventario_detalle_pkey PRIMARY KEY (id);


--
-- Name: revisiones_inventario revisiones_inventario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.revisiones_inventario
    ADD CONSTRAINT revisiones_inventario_pkey PRIMARY KEY (id);


--
-- Name: socios socios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.socios
    ADD CONSTRAINT socios_pkey PRIMARY KEY (id);


--
-- Name: revisiones_inventario_detalle uk9s87hysbfsd5ixkm2tr9d90ox; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.revisiones_inventario_detalle
    ADD CONSTRAINT uk9s87hysbfsd5ixkm2tr9d90ox UNIQUE (revision_id, elemento_id);


--
-- Name: socios ukaogtxbnnm2o5mlm6xb963rptw; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.socios
    ADD CONSTRAINT ukaogtxbnnm2o5mlm6xb963rptw UNIQUE (numero_socio);


--
-- Name: inventario ukd6d1h2cgqw41yikwobahvcsrr; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario
    ADD CONSTRAINT ukd6d1h2cgqw41yikwobahvcsrr UNIQUE (codigo);


--
-- Name: usuarios ukm2dvbwfge291euvmk6vkkocao; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT ukm2dvbwfge291euvmk6vkkocao UNIQUE (username);


--
-- Name: configuracion_cuadrillas ukpnaupwe5bly38sjdqcubjipu3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.configuracion_cuadrillas
    ADD CONSTRAINT ukpnaupwe5bly38sjdqcubjipu3 UNIQUE (nombre);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: revisiones_inventario_detalle fk4x6w9w4o13t38rxt8a2jetts8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.revisiones_inventario_detalle
    ADD CONSTRAINT fk4x6w9w4o13t38rxt8a2jetts8 FOREIGN KEY (revision_id) REFERENCES public.revisiones_inventario(id);


--
-- Name: cuotas fkf79j61mr676094db6fsgjbrqr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cuotas
    ADD CONSTRAINT fkf79j61mr676094db6fsgjbrqr FOREIGN KEY (socio_id) REFERENCES public.socios(id);


--
-- Name: revisiones_inventario_detalle fkmehdhnfkjcpxn60e4r5i3yip0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.revisiones_inventario_detalle
    ADD CONSTRAINT fkmehdhnfkjcpxn60e4r5i3yip0 FOREIGN KEY (elemento_id) REFERENCES public.inventario(id);


--
-- PostgreSQL database dump complete
--

\unrestrict HOe1AsBcUHntUtjqfPmDJvhHMUwtlE3EhHnnojtqh5exmZO6g9AituaIL7PqCBg

