spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

server.address=127.0.0.1
jwt.secret=${JWT_SECRET}

app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN}

spring.jpa.open-in-view=false

spring.flyway.enabled=true
