spring.application.name=gestion-hermandad

spring.datasource.url=jdbc:postgresql://localhost:5432/Hermandad
spring.datasource.username=postgres
spring.datasource.password=admin17

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081

jwt.secret=MiClaveSuperSecretaParaHermandad2026ConMasDe32CaracteresParaJWT
