-- Initial schema matched to produccion_schema.sql (PostgreSQL 18.6).
-- Source SHA-256: 8D599C12B3CA21CCDC4C3DD7B00E090CBB0B2806062528EED2FA20E01D2B23A2
-- EMPTY databases only. Existing production must be explicitly baselined at 1.
-- Preserve column order and constraint/index names for future migrations.
-- Unqualified names use Flyway's selected schema (public in production).
-- Standard IN checks / inline identity syntax also allow H2 tests; PostgreSQL
-- catalog and schema-only dump equivalence are verified against the source.

CREATE TABLE auditoria (
    id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 CACHE 1) NOT NULL,
    accion character varying(255),
    entidad character varying(255),
    fecha timestamp(6) without time zone,
    registro_id bigint,
    usuario character varying(255)
);

CREATE TABLE configuracion (
    id bigint NOT NULL,
    anio_activo integer,
    cif character varying(255),
    direccion character varying(255),
    email character varying(255),
    iban character varying(255),
    importe_cuota_costalero numeric(38,2),
    importe_cuota_hermano numeric(38,2),
    nombre_hermandad character varying(255),
    telefono character varying(255)
);

CREATE TABLE configuracion_cuadrillas (
    id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 CACHE 1) NOT NULL,
    columnas integer NOT NULL,
    filas integer NOT NULL,
    nombre character varying(120) NOT NULL
);

CREATE TABLE cuotas (
    id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 CACHE 1) NOT NULL,
    anio integer,
    estado character varying(255),
    fecha_pago date,
    importe numeric(38,2),
    observaciones character varying(255),
    tipo character varying(255) NOT NULL,
    socio_id bigint,
    CONSTRAINT cuotas_estado_check CHECK (CAST(estado AS text) IN (CAST(CAST('PENDIENTE' AS character varying) AS text), CAST(CAST('PAGADA' AS character varying) AS text), CAST(CAST('ANULADA' AS character varying) AS text))),
    CONSTRAINT cuotas_tipo_check CHECK (CAST(tipo AS text) IN (CAST(CAST('HERMANO' AS character varying) AS text), CAST(CAST('COSTALERO' AS character varying) AS text)))
);

CREATE TABLE inventario (
    id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 CACHE 1) NOT NULL,
    activo boolean NOT NULL,
    categoria character varying(255) NOT NULL,
    codigo character varying(255) NOT NULL,
    descripcion character varying(2000),
    estado character varying(255) NOT NULL,
    fecha_adquisicion date,
    imagen_url character varying(255),
    nombre character varying(255) NOT NULL,
    observaciones character varying(2000),
    ubicacion character varying(255) NOT NULL,
    valor_adquisicion numeric(12,2),
    CONSTRAINT inventario_estado_check CHECK (CAST(estado AS text) IN (CAST(CAST('BUENO' AS character varying) AS text), CAST(CAST('REGULAR' AS character varying) AS text), CAST(CAST('DETERIORADO' AS character varying) AS text), CAST(CAST('RESTAURACION' AS character varying) AS text), CAST(CAST('EXTRAVIADO' AS character varying) AS text)))
);

CREATE TABLE revisiones_inventario (
    id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 CACHE 1) NOT NULL,
    estado character varying(255) NOT NULL,
    fecha timestamp(6) without time zone NOT NULL,
    observaciones character varying(2000),
    titulo character varying(255) NOT NULL,
    usuario character varying(255) NOT NULL,
    CONSTRAINT revisiones_inventario_estado_check CHECK (CAST(estado AS text) IN (CAST(CAST('ABIERTA' AS character varying) AS text), CAST(CAST('CERRADA' AS character varying) AS text)))
);

CREATE TABLE revisiones_inventario_detalle (
    id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 CACHE 1) NOT NULL,
    estado_observado character varying(255),
    fecha_verificacion timestamp(6) without time zone,
    incidencia character varying(2000),
    ubicacion_observada character varying(255),
    verificado boolean NOT NULL,
    elemento_id bigint NOT NULL,
    revision_id bigint NOT NULL,
    CONSTRAINT revisiones_inventario_detalle_estado_observado_check CHECK (CAST(estado_observado AS text) IN (CAST(CAST('BUENO' AS character varying) AS text), CAST(CAST('REGULAR' AS character varying) AS text), CAST(CAST('DETERIORADO' AS character varying) AS text), CAST(CAST('RESTAURACION' AS character varying) AS text), CAST(CAST('EXTRAVIADO' AS character varying) AS text)))
);

CREATE TABLE socios (
    id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 CACHE 1) NOT NULL,
    apellidos character varying(255) NOT NULL,
    cuadrilla character varying(120),
    direccion character varying(255),
    dni character varying(9) NOT NULL,
    email character varying(255),
    estado character varying(255),
    fecha_alta date,
    fecha_creacion timestamp(6) without time zone,
    fecha_modificacion timestamp(6) without time zone,
    fecha_nacimiento date,
    forma_pago character varying(255),
    iban character varying(34),
    nombre character varying(255) NOT NULL,
    numero_socio integer,
    posicion_cuadrilla integer,
    telefono character varying(255),
    tipo character varying(255) NOT NULL,
    titular_cuenta character varying(255),
    CONSTRAINT socios_estado_check CHECK (CAST(estado AS text) IN (CAST(CAST('ACTIVO' AS character varying) AS text), CAST(CAST('BAJA' AS character varying) AS text), CAST(CAST('FALLECIDO' AS character varying) AS text), CAST(CAST('SUSPENDIDO' AS character varying) AS text))),
    CONSTRAINT socios_forma_pago_check CHECK (CAST(forma_pago AS text) IN (CAST(CAST('EFECTIVO' AS character varying) AS text), CAST(CAST('TRANSFERENCIA' AS character varying) AS text), CAST(CAST('DOMICILIACION' AS character varying) AS text))),
    CONSTRAINT socios_tipo_check CHECK (CAST(tipo AS text) IN (CAST(CAST('HERMANO' AS character varying) AS text), CAST(CAST('COSTALERO' AS character varying) AS text)))
);

CREATE TABLE usuarios (
    id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 CACHE 1) NOT NULL,
    activo boolean,
    password character varying(255),
    rol character varying(255),
    username character varying(255),
    CONSTRAINT usuarios_rol_check CHECK (CAST(rol AS text) IN (CAST(CAST('ADMIN' AS character varying) AS text), CAST(CAST('TESORERO' AS character varying) AS text), CAST(CAST('SECRETARIO' AS character varying) AS text), CAST(CAST('CONSULTA' AS character varying) AS text)))
);

ALTER TABLE auditoria
    ADD CONSTRAINT auditoria_pkey PRIMARY KEY (id);

ALTER TABLE configuracion_cuadrillas
    ADD CONSTRAINT configuracion_cuadrillas_pkey PRIMARY KEY (id);

ALTER TABLE configuracion
    ADD CONSTRAINT configuracion_pkey PRIMARY KEY (id);

ALTER TABLE cuotas
    ADD CONSTRAINT cuotas_pkey PRIMARY KEY (id);

ALTER TABLE inventario
    ADD CONSTRAINT inventario_pkey PRIMARY KEY (id);

ALTER TABLE revisiones_inventario_detalle
    ADD CONSTRAINT revisiones_inventario_detalle_pkey PRIMARY KEY (id);

ALTER TABLE revisiones_inventario
    ADD CONSTRAINT revisiones_inventario_pkey PRIMARY KEY (id);

ALTER TABLE socios
    ADD CONSTRAINT socios_pkey PRIMARY KEY (id);

ALTER TABLE revisiones_inventario_detalle
    ADD CONSTRAINT uk9s87hysbfsd5ixkm2tr9d90ox UNIQUE (revision_id, elemento_id);

ALTER TABLE socios
    ADD CONSTRAINT ukaogtxbnnm2o5mlm6xb963rptw UNIQUE (numero_socio);

ALTER TABLE inventario
    ADD CONSTRAINT ukd6d1h2cgqw41yikwobahvcsrr UNIQUE (codigo);

ALTER TABLE usuarios
    ADD CONSTRAINT ukm2dvbwfge291euvmk6vkkocao UNIQUE (username);

ALTER TABLE configuracion_cuadrillas
    ADD CONSTRAINT ukpnaupwe5bly38sjdqcubjipu3 UNIQUE (nombre);

ALTER TABLE usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);

ALTER TABLE revisiones_inventario_detalle
    ADD CONSTRAINT fk4x6w9w4o13t38rxt8a2jetts8 FOREIGN KEY (revision_id) REFERENCES revisiones_inventario(id);

ALTER TABLE cuotas
    ADD CONSTRAINT fkf79j61mr676094db6fsgjbrqr FOREIGN KEY (socio_id) REFERENCES socios(id);

ALTER TABLE revisiones_inventario_detalle
    ADD CONSTRAINT fkmehdhnfkjcpxn60e4r5i3yip0 FOREIGN KEY (elemento_id) REFERENCES inventario(id);
